### ISSUE TITLE
Om Next Quickstart AnimalsList demo fails at runtime

### ISSUE THREAD

**Issue by thos37** [omcljs/om#392]
From the Quickstart, the AnimalsList demo fails to run with the following error in the console:
```
Uncaught Error: Assert failed: (gdom/isElement target)
```
I tried changing this:

```clojure
(om/add-root! reconciler
              AnimalsList (gdom/getElement "app"))
```
to this:
```clojure
(om/add-root! reconciler
              (gdom/getElement "app") AnimalsList)
```
but now it throws this error at the same place:
```
Uncaught Error: nth not supported on this type cljs.core/Keyword
```
```
Uncaught Error: nth not supported on this type
cljs.core/Keywordcljs.core.nth.cljs$core$IFn$_invoke$arity$3 
@ core.cljs:1678cljs$core$nth 
@ core.cljs:1617om$next$build_index_STAR_ 
@ next.cljs:559om.next.Indexer.om$next$protocols$IIndexer$index_root$arity$2 
@ next.cljs:565om$next$protocols$index_root 
@ protocols.cljs:5om.next.Reconciler.om$next$protocols$IReconciler$add_root_BANG_$arity$4 
@ next.cljs:711om$next$protocols$add_root_BANG_ 
@ protocols.cljs:13om.next.add_root_BANG_.cljs$core$IFn$_invoke$arity$4 
@ next.cljs:434om$next$add_root_BANG_ 
@ next.cljs:422om.next.add_root_BANG_.cljs$core$IFn$_invoke$arity$3 
@ next.cljs:431om$next$add_root_BANG_ 
@ next.cljs:422(anonymous function) 
@ core.cljs:232
utils.cljs:36 Figwheel: trying to open cljs reload socket
```

**Comment by shofetim** [comment]
The first form

```
(om/add-root! reconciler
              AnimalsList (gdom/getElement "app"))
```

Appears correct. Do you have an element with id "app" in your index.html?

**Comment by anmonteiro** [comment]
I was getting the same error, and solved by downloading the repository again.
You're probably a few commits behind; [download master](https://github.com/omcljs/om/archive/master.zip) again and run `lein install`. Don't forget to run `lein clean`.

**Comment by fragamus** [comment]
@anmonteiro I did all that you suggest and I still get

Uncaught Error: nth not supported on this type

**Comment by thos37** [comment]
Eventually I got it to work without changing the code.  I'm not sure which did it, but I started with a fresh lein clean, lein install in the om project, then a lein clean in the tutorial project, and finally I tried a (clean-builds) from within the figwheel REPL, as well as deleting the om jar from my local maven store.  Eventually one or all of those worked.
