### ISSUE TITLE
React.render throws a deprecation warning in JS console

### ISSUE THREAD

**Issue by mulchy** [omcljs/om#419]
I was working through the om.next tutorial and noticed that `React.render` produced a deprecation warning suggesting the use of `ReactDOM.render` instead. I updated the QuickStart wiki page locally at https://github.com/mulchy/om/wiki to use this namespace instead. Unfortunately there is no easy way to make a PR for wiki edits, but if you would like you can clone my version of the wiki https://github.com/mulchy/om.wiki.git and get my commit.

Thanks for making these tutorials!

**Comment by swannodette** [comment]
Already been fixed in alpha2

**Comment by mulchy** [comment]
You are too fast for me. Thanks!

**Comment by vikeri** [comment]
Hmm, still getting the same issue from the code here: https://github.com/omcljs/om/wiki/Quick-Start-%28om.next%29#your-first-component
