### ISSUE TITLE
Defaulting key to undefined in build

### ISSUE THREAD

**Issue by SevereOverfl0w** [omcljs/om#673]
https://github.com/omcljs/om/blob/master/src/main/om/core.cljs#L967

The `:key` prop is merged in as `undefined` if not provided in the multi-arity version of the function. This results in multiple components having the same key if they are built adjacently.

I propose that if the key isn't present, it's simply not merged in. I can make a PR, but I wanted to discuss first in case there's a good reason for this behavior, there's a comment beside it, but no real expansion on why.

**Comment by bendlas** [comment]
This problem also exists in om.next: https://github.com/omcljs/om/blob/master/src/main/om/next.cljs#L338

It needs to be fixed, as it's a massive problem with react 15.

**Comment by bendlas** [comment]
I'm not getting the warning any more with React `15.1.0`. My examples alse seem to work. Can somebody verify that this was fixed upstream?

**Comment by maxcountryman** [comment]
@bendlas updating React in my project does not seem to fix the issue for me.

**Comment by swannodette** [comment]
It was done that way for a reason. I'd like a see a minimal example of when this doesn't work first thanks.

**Comment by maxcountryman** [comment]
@swannodette I ran into the issue doing something similar to:

```clojure
(defui FirstInput
  Object
  (render [this]
    (dom/input #js {:id "first" :name "first" :type "text" :value "first"})))

(def first-input (om/factory FirstInput))

(defui SecondInput
  Object
  (render [this]
    (dom/input #js {:id "second" :name "second" :type "second" :value "second"})))

(def second-input (om/factory SecondInput))

(defui Form
  Object
  (render [this]
      (dom/div nil
        (dom/h2 nil "Form")
        (dom/form nil
          (first-input)
          (second-input)
          (dom/button nil "Submit")))))

(defonce reconciler
  (om/reconciler
    {:state (atom {})}))

(om/add-root! reconciler
  Form (gdom/getElement "app"))
```

**Comment by swannodette** [comment]
fixed in master due to React bump

**Comment by maxcountryman** [comment]
Thanks, David!
